name: Fetch Metrics of Worldcoin Daily

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0 点运行
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT

      - name: Fetch metrics from Worldcoin
        run: |
          mkdir -p metrics
          curl -s "https://metrics.worldcoin.org/" -o "metrics/${{ steps.get-timestamp.outputs.timestamp }}.json"
          echo "Fetched and saved to metrics/${{ steps.get-timestamp.outputs.timestamp }}.json"

      - name: Commit and push new metrics file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics/*.json
          git commit -m "Add metrics for ${{ steps.get-timestamp.outputs.timestamp }} UTC" || echo "Nothing to commit"
          git push
